version: '3.8'

services:
  php:
    build:
      context: ./
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - pgsql
    networks:
      - default

  pgsql:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    networks:
      - default

networks:
  default:
    driver: bridge